model_name: unsloth/gemma-2-9b-it-bnb-4bit
max_seq_length: 2048
load_in_4bit: true
r: 16
target_modules: 
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_alpha: 16
lora_dropout: 0
bias: none
use_gradient_checkpointing: unsloth
random_state: 4237
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
warmup_steps: 5
warmup_ratio: 0.1
num_train_epochs: 1
max_steps: -1
learning_rate: 2e-5
logging_steps: 25
weight_decay: 0.01
dataset_num_proc: 4
packing: true
optim: adamw_8bit
lr_scheduler_type: linear
output_dir: /mnt/g/modelville/lck
push_to_hub: true
hf_username: lckidwell
trained_model_name: muddylemon
dataset_file: /mnt/g/modelville/datasets/lckidwell/
export_to_ollama: false
eval_steps: 100
evaluation_strategy: steps
save_steps: 100

