creator_type: TweetDatasetCreator
formatter: TweetCompletionFormatter
input_file: ./data/muddylemon-tweets.js
output_file: ./datasets/muddylemon-completion-dataset.json
twitter_username: nuddylemon
min_tweet_length: 20